# Generated by Django 5.2.6 on 2025-09-11 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='timeCreated',
            new_name='time',
        ),
    ]
