# Generated by Django 5.2.6 on 2025-09-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_score_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='user',
        ),
    ]
