# Generated by Django 5.2.6 on 2025-10-04 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_score_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='score',
        ),
    ]
